login: &login
  adapter: mysql2
  host: localhost
  username: okaapi
  password: 0kap1
  encoding: utf8
  
development:
  database: geni
  <<: *login

production:
  database: geni	
  <<: *login

test:
  database: geni_test
  <<: *login
